SELECT   N_NAME, SUM(L_QUANTITY) as QUANTIDADE
FROM     NATION, ORDERS, CUSTOMER, LINEITEM
WHERE    N_NATIONKEY = C_NATIONKEY AND 
         C_CUSTKEY = O_CUSTKEY     AND 
         O_ORDERKEY = L_ORDERKEY
GROUP BY N_NAME 
ORDER BY QUANTIDADE  DESC LIMIT 10;
