SELECT COUNT(*)
FROM (
    SELECT DISTINCT(C_CUSTKEY)
    FROM CUSTOMER LEFT JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
    EXCEPT 
    SELECT DISTINCT(C_CUSTKEY)
    FROM CUSTOMER INNER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
);
